#!/bin/sh
# script/bootstrap: Download dependencies required.
# gems
# Missing/assumed present: rbenv, ruby, bundler, postgres

if ! brew ls --versions ImageMagick > /dev/null ; then
  echo "==> Installing ImageMagick via homebrew..."
  brew install ImageMagick
fi

if ! brew ls --versions redis > /dev/null ; then
  echo "==> Installing Redis via homebrew..."
  brew install redis
fi

# install gems
bundle install
