#!/bin/sh
# script/test: run test suite, connected to dependencies in Pilot.

set -e

usage() {
  echo "Usage: script/test [options (optional)] [spec paths]"
  echo " options:"
  echo "    -h show help"

  exit 1;
}

# if [ -z "$1" ]; then
#   usage
# fi

while getopts ":h" opt; do
  case $opt in
    h)
      usage
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
  esac
done
shift "$((OPTIND-1))"

DIR=`dirname $0`

rspec "$@"
